#%RAML 0.8
---
title: TAS core
baseUri: http://talentappstore.com/{version}
version: v1

/apps:
  /{consumingApp}:
    description: the name of the app consuming the API, typically the one asking for an accessor
    /tenants:
      /{tenant}:
      description: tenant name
        /accessors:
          /{apiDeveloper}:
            description: the developer who owns the API
            /{apiUriTemplate}:
              description: the URI template (as per RFC blah) of the API
              get:
                description: 
                  obtain accessor(s) for each producer of a specific API that we wish to consume
                  invalidates any existing tokens - SAY WHAT? SURELY JUST RETURNS EXISTING ONES? WHAT ABOUT EXPIRY?
                queryParameters:
                  jwtId:
                    description: id of the JWT containing user identity, as obtained from the SAML assertion and stored by TAS
                  accessToken:
                    description: |
                      the access token passed in to the consuming app, which indirectly identifies the principal.
                      Once this API call has created new tokens, no relationship (expiry or otherwise) exists
                      to this token. 
                responses:
                  200:
                    body:
                      application/json:
                        schema: !include ../schemas/accessors.json
                        example: !include ../examples/accessors.json
              /{producingApp}:
                /credentials:
                  description: get credentials for the specified accessor
                  get:


{
    "accessors": [
	{
		"kind": "accessor",
		"producer": "crazyjobs",
		"location": "https://acme.crazyjobs:2109/api/v3.2/tenants/{tenant}",
		"auth": {"type": "HMAC", "credentials": {"publicKey": "kjh876gk96rf0978", "secretKey": "k8763216548hppou", "expires": "23-OCT-2099-13:00:23:45" }}
	},
	{
		"kind": "accessor",
		"producer": "jobcopier",
		"location": "https://jobcopier.com:2102/acme/api/v3/cust/{tenant}",
		"auth": {"type": "HMAC", "credentials": {"publicKey": "89ujg764447786gh", "secretKey": "06jjj765hgu76511", "expires": "23-OCT-2099-13:00:23:45" }}
	}
    ]
}


